#!/bin/bash

DATE_TIME=$(date +%Y%m%d_%H%M%S)
URL=http://sfsuswe.com/svn
USER_DIR=f14g10

svn mkdir -m "Making a new tag dir - $DATE_TIME" $URL/$USER_DIR/tag/$DATE_TIME

echo "Made new tag directory $DATE_TIME"

echo "Copying previous trunk into tag/$DATE_TIME"

svn cp -m "Moving /trunk to tag/$DATE_TIME/" $URL/$USER_DIR/trunk $URL/$USER_DIR/tag/$DATE_TIME/.

echo "Make sure to wipe old /trunk" 

svn delete -m "Erasing old /trunk/" $URL/$USER_DIR/trunk

echo "Copying 'branch' into /trunk to make new stable version"

svn cp -m "Making a copy of 'branch' into /trunk so it becomes the new stable version" $URL/$USER_DIR/branch $URL/$USER_DIR/trunk
